apiVersion: v1
kind: ServiceAccount
metadata:
  name: squid
  namespace: internet-egress
automountServiceAccountToken: false
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: internet-egress
  name: psp:squid
rules:
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]
    resourceNames: ["squid"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: internet-egress
  name: squid:psp:squid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp:squid
subjects:
- kind: ServiceAccount
  name: squid
  namespace: internet-egress
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: squid
  namespace: internet-egress
data:
  squid.conf: |-
    acl neco_network src 10.64.0.0/12
    # Only allow cachemgr access from localhost
    http_access allow manager localhost
    http_access deny manager
    http_access allow neco_network
    http_access deny all
    http_port 3128
    access_log stdio:/var/log/squid/access.log
    pid_filename "none"
    cache_dir aufs /var/spool/squid 50000 16 256
    coredump_dir /var/spool/squid
    cache_mem 6 GB
    maximum_object_size_in_memory 100 MB
    maximum_object_size 100 MB
    detect_broken_pconn on
    forwarded_for delete
    httpd_suppress_version_string on
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: squid
  namespace: internet-egress
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: squid
  template:
    metadata:
      labels:
        app.kubernetes.io/name: squid
        k8s-app: squid
    spec:
      # system priority class cannot be specified for pods in namespaces
      # other than kube-system as of k8s 1.12.
      # see https://github.com/kubernetes/kubernetes/pull/65593
      #priorityClassName: system-cluster-critical
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
        - key: CriticalAddonsOnly
          operator: Exists
      dnsConfig:
        nameservers:
          - 127.0.0.1
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - squid
              topologyKey: "cke.cybozu.com/rack"
      serviceAccountName: squid
      containers:
        - name: squid
          image: {{ .squid }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /var/spool/squid
              name: cache
            - mountPath: /etc/squid
              name: config
          ports:
           - name: proxy
             containerPort: 3128
             protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - CHOWN
                - SETUID
                - SETGID
              drop:
                - all
            readOnlyRootFilesystem: true
          livenessProbe:
            tcpSocket:
              port: 3128
            periodSeconds: 1
            initialDelaySeconds: 10
            failureThreshold: 6
        - name: unbound
          image: {{ index . "cke-unbound" }}
          imagePullPolicy: IfNotPresent
          args:
            - -c
            - /etc/unbound/unbound.conf
          volumeMounts:
            - name: config-volume
              mountPath: /etc/unbound
              readOnly: true
            - name: temporary-volume
              mountPath: /tmp
          ports:
            - containerPort: 53
              name: dns
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - all
            readOnlyRootFilesystem: true
          resources:
            limits:
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 256Mi
          livenessProbe:
            tcpSocket:
              port: 53
              host: 127.0.0.1
            periodSeconds: 1
            initialDelaySeconds: 1
            failureThreshold: 6
      volumes:
        - name: cache
          emptyDir: {}
        - name: config
          configMap:
            name: squid
            items:
              - key: squid.conf
                path: squid.conf
        - name: config-volume
          configMap:
            name: unbound
            items:
              - key: unbound.conf
                path: unbound.conf
              - key: root.hints
                path: root.hints
        - name: temporary-volume
          emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: squid
  namespace: internet-egress
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: squid
  ports:
    - protocol: TCP
      nodePort: 30128
      port: 3128
      targetPort: 3128
